spring:
  application:
    name: nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: nacos-privider
          uri: lb://nacos-privider
          predicates:
            - Path=/privider/**
          filters:
            - StripPrefix=1
server:
  port: 8084